name: Latest Youtube Videos
on:
  schedule: # Run workflow automatically
    - cron: "* * * * 5,6,0"
  push:
  pull_request:
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest Youtube Videos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?playlist_id=PL7CcGwsqRpSM3w9BT_21tUU8JN2SnyckR"
          max_post_count: 4
          comment_tag_name: "YOUTUBE"
